---
title: "NADM1 Data Cleaning"
author: "Daniel O'Leary"
date: "January 29, 2019"
output: 
  github_document:
    toc: true
---

# Setup

## Load Packages
```{r setup, include=FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  tidyverse, 
  haven, 
  lubridate
)
```


## Load Data
```{r}
subids <-
  read_csv("G:/My Drive/research/projects/nadm1/nadm1_data/nadm1_ssdm2_subids.csv")

redcap <-
  read_csv("G:/My Drive/research/projects/nadm1/nadm1_data/nadm1_redcap_data/nadm1_ema_01_29_1905.csv")

asa_24 <-
  read_csv("G:/My Drive/research/projects/nadm1/nadm1_data/nadm1_asa24_data/nadm1_2019-01-30_80657/nadm1_2019-01-30_80657_TNS.csv")

asa_24_total <-
  read_csv("G:/My Drive/research/projects/nadm1/nadm1_data/nadm1_asa24_data/nadm1_2019-01-30_80657/nadm1_2019-01-30_80657_Totals.csv")

# ssdm2_survey_data <-
#   ssdm2_survey_data %>% 
#   left_join(
#     ssdm2_mcq,
#     by = "subid"
#   )

ssdm2_survey_data_nadm <- 
  read_csv("G:/My Drive/research/projects/ssdm2/ssdm2_group_data/ssdm2_survey_data_new.csv") %>% 
  mutate(subid = as.numeric(subid))


# UPDATE THESE
# c_df_nadm <- read_csv("G:/My Drive/research/projects/ssdm2/ssdm2_group_data/ssdm2_choices_survey.csv")
# r_df_nadm <- read_csv("G:/My Drive/research/projects/ssdm2/ssdm2_group_data/ssdm2_ratings_survey.csv")
```
49 is fasting

```{r}
low_cals <- asa_24_total %>% filter(complete == "Y") %>% group_by(subid) %>% summarise(cals = mean(KCAL, na.rm = TRUE)) %>% filter(cals < 900)
```



```{r}
asa_24_total %>% 
  filter(complete == "Y") %>% 
  filter(subid %!in% low_cals$subid) %>% 
  dplyr::select(
    ses_comp_all,
    ses_subj_all,
    ladd_comm,
    soc_class,
    ladd_us,
    panas_neg,
    stai_trait,
    hese,
    effexp,
    health_lm_beta,
    taste_lm_beta,
    KCAL:A_DRINKS
  ) %>% 
  filter_all(
    all_vars(!is.na(.))
  ) %>% 
  mutate(
    vtotalleg = ( V_TOTAL + V_LEGUMES ) / (KCAL / 1000),
    vdrkgrleg = ( V_LEGUMES + V_DRKGR) / (KCAL / 1000),
    f_total = ( F_TOTAL ) / (KCAL / 1000),
    fwholefrt = ( F_OTHER ) / (KCAL / 1000),
    add_sugars_per = 100 * (ADD_SUGARS * 16 / KCAL), 
    sfat_perc = 100 * (SFAT * 9 / KCAL),
    
    hei = vtotalleg + vdrkgrleg + f_total + fwholefrt
  ) %>% 
  cor() %>% 
  round(., 2)

asa_24 %>% 
  dplyr::select(
    ses_comp_all,
    ses_subj_all,
    ladd_comm,
    soc_class,
    ladd_us,
    panas_neg,
    stai_trait,
    hese,
    effexp,
    health_lm_beta,
    taste_lm_beta,
    KCAL:B12_ADD
  ) %>% 
  filter_all(
    all_vars(!is.na(.))
  ) %>% 
  cor() %>% 
  round(., 2)
```

```{r}
asa_24_total_group <-
  asa_24_total %>% 
  mutate(
    healthy = (F_TOTAL/KCAL + V_TOTAL/KCAL + G_WHOLE/KCAL - ADD_SUGARS/KCAL) / 4
  ) %>% 
  group_by(subid) %>% 
  summarise(
    mean_health = mean(healthy, na.rm = TRUE)
  ) %>% 
  left_join(
    ssdm2_survey_data_nadm %>% 
      select(
        subid, 
        ses_comp_all,
        ses_subj_all,
        ladd_comm
      ),
    by = "subid"
  )

summary(lm(mean_health ~ ses_comp_all, data = asa_24_total_group))
```

```{r}
lm1 <-
  lmer(
    healthy ~
      ses_subj_all + 
      (1|subid) +
      (1|ReportingDate),
    data = asa_24_total
  )

summary(lm1)

lm1 <-
  lmer(
    V_TOTAL ~
      ses_subj_all + 
      (1|subid) +
      (1|ReportingDate),
    data = asa_24_total %>% filter(V_TOTAL < mean(V_TOTAL, na.rm = TRUE) + 4 * sd (V_TOTAL, na.rm = TRUE))
  )

summary(lm1)
```



```{r}
lm1 <-
  lmer(
    V_TOTAL ~
      ladd_comm +
      (1|subid),
    data = asa_24_total
  )

summary(lm1)
```


## mediation - 

```{r}
data <- 
  data.frame(
    X = asa_24_total$ladd_comm, 
    Y = asa_24_total$V_TOTAL, 
    M1 = asa_24_total$effexp, 
    M2 = asa_24_total$stai_trait
  )

model <- 
  '
    # direct effect
    Y ~ b1 * M1 + b2 * M2 + c * X
    
    # mediator
    M1 ~ a1 * X
    M2 ~ a2 * X
    
    
    # direct effect
    direct := c
    
    # indirect effect (a*b)
    indirect1 := a1 * b1
    indirect2 := a2 * b2
    
    
    # total effect
    total := c + (a1 * b1) + (a2 * b2)  
    prop_mediated := (abs(indirect1) + abs(indirect2) )/abs(total)
    
    # covariances
    
    M1 ~~ M2

'
fit <- 
  sem(
    model, 
    data = data
  )

summary(
  fit, 
  standardized = TRUE, 
  fit.measures = T, 
  rsq = T
)
```



```{r}
# ASA 24 by day

asa_24_by_day <-
  asa_24_total %>% 
  dplyr::select(
    subid = ssdm2_subid,
    day = ReportingDate,
    KCAL:A_DRINKS
  ) %>% 
  mutate(
    date = mdy(day)
  ) %>% 
  gather(food, amt, KCAL:A_DRINKS) %>% 
  group_by(subid, date, food) %>% 
  summarise(
    mean = mean(amt, na.rm = TRUE)
    #sd = sd(amt, na.rm = TRUE)
  ) %>% 
  ungroup() %>% 
  spread(food, mean)

asa_24_avg <-
  asa_24_total %>% 
  dplyr::select(
    subid = ssdm2_subid,
    KCAL:A_DRINKS
  ) %>% 
  gather(food, amt, KCAL:A_DRINKS) %>% 
  group_by(subid, food) %>% 
  summarise(
    mean = mean(amt, na.rm = TRUE)
    #sd = sd(amt, na.rm = TRUE)
  )  %>% 
  ungroup() %>% 
  spread(food, mean)

asa_24_avg <-
  asa_24_avg %>% 
  mutate(subid = as.numeric(subid)) %>% 
  left_join(
    ssdm2_survey_data_nadm,
    by = "subid"
  )
```

```{r}
redcap_by_day <-
  redcap_ema %>% 
  dplyr::select(
    subid,
    ema_survey_timestamp,
    anger:motivated
  ) %>% 
  mutate(
    date = date(ema_survey_timestamp),
    subid = as.numeric(subid)
  ) %>% 
  dplyr::select(-ema_survey_timestamp) %>% 
  gather(emotion, value, anger:motivated) %>% 
  group_by(subid, date, emotion) %>% 
  summarise(
    mean = mean(value, na.rm = TRUE)
  ) %>% 
  ungroup() %>% 
  spread(emotion, mean)
```

## by day DF

```{r}
by_day <-
  redcap_by_day %>% 
  filter(!is.na(date)) %>% 
  left_join(
    asa_24_by_day %>% mutate(subid = as.numeric(subid)),
    by = c("subid", "date")
  ) %>% 
  left_join(
    ssdm2_survey_data_nadm,
    by = "subid"
  )
```


## EMA emotions and SES

```{r}
by_day %>% 
  dplyr::select(
    ses_comp_all,
    ses_subj1,
    ladd_comm,
    food_cost_1,
    alert:worried
  ) %>% 
  filter_all(all_vars(!is.na(.))) %>% 
  cor() %>% 
  round(., 2)
```

```{r}
lm1 <-
  lm(
    positive ~
      ladd_comm, 
    data = by_day
  )

summary(lm1)

lm1 <-
  lmer(
    positive ~
      ladd_comm +
      (1|subid), 
    data = by_day
  )

summary(lm1)
```


## SES and food

```{r}
by_day %>% 
  dplyr::select(
    ses_comp_all,
    ses_subj_all,
    ladd_comm,
    food_cost_1,
    A_DRINKS:ZINC
  ) %>% 
  filter_all(all_vars(!is.na(.))) %>% 
  cor() %>% 
  round(., 2)
```


## Betas and food

```{r}

by_day %>% 
  dplyr::select(
    health_lm_beta,
    taste_lm_beta,
    A_DRINKS:ZINC
  ) %>% 
  filter_all(all_vars(!is.na(.))) %>% 
  cor()
```

```{r}
lm1 <-
  lmer(
    V_TOTAL ~
      ladd_comm +
      (1|subid) + (1|date),
    data = by_day
  )

summary(lm1)

lm1 <-
  lmer(
    V_DRKGR ~
      ladd_comm +
      (1|subid) + (1|date),
    data = by_day
  )

summary(lm1)
```




## EMA emotions and food

```{r}
by_day %>% 
  dplyr::select(
    alert:worried,
    KCAL,
    V_TOTAL,
    V_DRKGR,
    F_TOTAL,
    ADD_SUGARS,
    SOLID_FATS
  ) %>% 
  filter_all(all_vars(!is.na(.))) %>% 
  cor()
```


## linear model - health beta - food groups

```{r}
lm1 <-
  lm(
    health_lm_beta ~
      V_TOTAL + F_TOTAL + G_WHOLE + ADD_SUGARS,
    data = by_day
  )

summary(lm1)

lm1 <-
  lmer(
    V_TOTAL ~
      health_lm_beta +
      (1|subid) + (1|date),
    data = by_day
  )

summary(lm1)
```

##

```{r}
by_day %>% 
  ggplot(aes(health_lm_beta, V_TOTAL)) + 
  #geom_point(alpha = 0.4) +
  geom_smooth(method = "lm")
```



##

```{r}
x_train <- 
  by_day %>% 
  select(A_DRINKS:ZINC) %>% 
  as.matrix()

y_train <-
  by_day %>% 
  select(health_lm_beta) %>% 
  as.matrix()

data <-
  by_day %>% 
  select(ses_subj1, A_DRINKS:ZINC) %>% 
  filter_all(all_vars(!is.na(.)))
  

my_grid <- 
  expand.grid(
    alpha = 0:1,
    lambda = seq(0.0001, 1, length = 20)
  )

set.seed(42)

rr_finals_fit1 <-
  train(
    # x_train,
    # y_train,
    ses_subj1 ~ .,
    data = data,
    method = "glmnet",
    preProc = c('scale','center'), 
    trControl = 
      trainControl(
        method = "cv", 
        number = 5
      )
  )

rr_finals_mod1 <- rr_finals_fit1$finalModel
```

```{r}
round(coef(rr_finals_fit1$finalModel, rr_finals_fit1$bestTune$lambda), 2)


tmp_coeffs <- coef(rr_finals_fit1$finalModel, rr_finals_fit1$bestTune$lambda)

coefs <- 
  data.frame(name = tmp_coeffs@Dimnames[[1]][tmp_coeffs@i + 1], coefficient = tmp_coeffs@x)

coefs %>%
  filter(name != "(Intercept)") %>% 
  ggplot(aes(fct_reorder(name, coefficient), coefficient)) +
  geom_point() +
  coord_flip()
```


```{r}
lm1 <-
  lm(
    V_DRKGR ~
      positive,
    data = by_day
  )

summary(lm1)
```


```{r}
lm1 <-
  lm(
    ADD_SUGARS ~
      cesd,
    data = asa_24_avg
  )

summary(lm1)
```




```{r}
lm1 <-
  lm(
    ADD_SUGARS ~
      cesd,
    data = asa_24_avg
  )

summary(lm1)
```




```{r}
cal_stress <-
  asa_24_total %>% 
  group_by(redcap_record_id, RecallNo) %>% 
  summarise(
    mean_v = mean(V_TOTAL, na.rm = TRUE)
  ) %>% 
  mutate(day = RecallNo) %>% 
  left_join(
    redcap_ema %>% 
      group_by(redcap_record_id, day) %>% 
      summarise(
        mean_stress = mean(stress, na.rm = TRUE),
        mean_worried = mean(worried, na.rm = TRUE)
      ) %>% 
      mutate(
        day = as.integer(str_extract(day, "\\d"))
      ),
    by = c("redcap_record_id","day")
  )

summary(lmer(mean_v ~ mean_stress + (1|redcap_record_id), data = cal_stress))

summary(lmer(V_TOTAL ~ gen_eating_15 + (1|ssdm2_subid), data = asa_24_total))
```

```{r}
asa_24_total <-
  asa_24_total %>% 
  left_join(
    rating_lm_betas,
    by = "subid"
  )

summary(lmer(FIBE ~ health_lm_beta + taste_lm_beta + (1|ssdm2_subid), data = asa_24_total))
summary(lmer(V_TOTAL ~ health_lm_beta + taste_lm_beta + (1|ssdm2_subid), data = asa_24_total))
summary(lmer(ADD_SUGARS ~ health_lm_beta + taste_lm_beta + (1|ssdm2_subid), data = asa_24_total))
summary(lmer(G_REFINED ~ health_lm_beta + taste_lm_beta + (1|ssdm2_subid), data = asa_24_total))
summary(lmer(F_TOTAL ~ health_lm_beta + taste_lm_beta + (1|ssdm2_subid), data = asa_24_total))
summary(lmer(SUGR ~ health_lm_beta + taste_lm_beta + (1|ssdm2_subid), data = asa_24_total))
summary(lmer(SOLID_FATS ~ health_lm_beta + taste_lm_beta + (1|ssdm2_subid), data = asa_24_total))

```

